// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.github.yiwkr.mattermost-plugin-janken",
  "name": "Janken",
  "description": "This plugin provide /janken command.",
  "version": "0.0.2",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "trigger",
        "display_name": "Trigger",
        "type": "text",
        "help_text": "Command trigger (default to \"janken\")",
        "placeholder": "",
        "default": "janken"
      },
      {
        "key": "defaultLanguage",
        "display_name": "DefaultLanguage",
        "type": "dropdown",
        "help_text": "Default Language (default to \"English\")",
        "placeholder": "",
        "default": "en",
        "options": [
          {
            "display_name": "English",
            "value": "en"
          },
          {
            "display_name": "日本語",
            "value": "ja"
          }
        ]
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
