ConfigDialogDestroyLabel = "Destroy this game"
ConfigDialogMaxRoundsLabel = "Max rounds"
ConfigDialogSubmitLabel = "Save"
ConfigDialogTitle = "Config"
ConfigPermissionErrorMessage = "Failed to open the configration dialog. The creator of this game or the administrator can configure the game."
HandsRegisteredMessage = "Your hands {{.HandsStr}} are registered with janken game ({{.ID}})."
JankenGameConfigButtonLabel = "Config"
JankenGameDescription = "Please join this janken game.\nParticipants ({{.ParticipantsNum}}): {{.ParticipantsStr}}"
JankenGameDestroyedMessage = "This janken game was destroyed by @{{.Username}}."
JankenGameJoinButtonLabel = "Join"
JankenGameResultButtonLabel = "Result"
JankenGameTitle = "Janken Game ({{.ID}}) created by @{{.Username}}"
JoinDialogCancelLabel = "Cancel"
JoinDialogHandElementHelp = "Choose hand {{.Index}}"
JoinDialogHandElementLabel = "Hand {{.Index}}"
JoinDialogHandPaper = "Paper"
JoinDialogHandRock = "Rock"
JoinDialogHandScissors = "Scissors"
JoinDialogSubmitLabel = "Save"
JoinDialogTitle = "Join the janken game"
ResultNotEnoughParticipantsErrorMessage = "Failed to show the result of the janken game. Least 2 pariticipants are required."
ResultPermissionErrorMessage = "Failed to show the result of the janken game. The creator of this game or the administrator can show the result."
ResultTableHandsLabel = "Hands"
ResultTableRankLabel = "Rank"
ResultTableTitle = "**Janken Game ({{.ID}})**\nResult\n"
ResultTableUsernameLabel = "Username"
