ConfigPermissionErrorMessage = "Failed to open the configration dialog. The creator of this game or the administrator can configure the game."
FailedToGetStoredGameErrorMessage = "Failed to get stored game data. Try to create another game."
HandsRegisteredMessage = "Your hands {{.HandsStr}} are registered with janken game ({{.ID}})."
ResultNotEnoughParticipantsErrorMessage = "Failed to show the result of the janken game. Least 2 pariticipants are required."
ResultPermissionErrorMessage = "Failed to show the result of the janken game. The creator of this game or the administrator can show the result."
ResultTableHandsLabel = "Hands"
ResultTableRankLabel = "Rank"
ResultTableTitle = "**Janken game ({{.ID}})**\nResult\n"
ResultTableUsernameLabel = "Username"
configDialogDestroyLabel = "Destroy this game"
configDialogMaxRoundsLabel = "Max rounds"
configDialogSubmitLabel = "Save"
configDialogTitle = "Config"
gameConfigButtonLabel = "Config"
gameDescription = "Please join this janken game.\nparticipants ({{.participantsNum}}): {{.participantsStr}}"
gameDestroyedMessage = "This janken game was destroyed by @{{.Username}}."
gameJoinButtonLabel = "Join"
gameResultButtonLabel = "Result"
gameTitle = "Janken game ({{.ID}}) created by @{{.Username}}"
joinDialogCancelLabel = "Cancel"
joinDialogHandElementHelp = "Choose hand {{.Index}}"
joinDialogHandElementLabel = "Hand {{.Index}}"
joinDialogHandPaper = "Paper"
joinDialogHandRock = "Rock"
joinDialogHandScissors = "Scissors"
joinDialogSubmitLabel = "Save"
joinDialogTitle = "Join the janken game"
