# janken game
JankenGameTitle = "Janken Game ({{.ID}}) created by @{{.Username}}"
JankenGameDescription = "Please join this janken game.\nParticipants ({{.ParticipantsNum}}): {{.ParticipantsStr}}"
JankenGameJoinButtonLabel = "Join"
JankenGameConfigButtonLabel = "Config"
JankenGameResultButtonLabel = "Result"

# Join
JoinDialogTitle = "Join the janken game"
JoinDialogSubmitLabel = "Save"
JoinDialogHandElementLabel = "Hand {{.Index}}"
JoinDialogHandElementHelp = "Choose hand {{.Index}}"
rock = "Rock"
scissors = "Scissors"
paper = "Paper"
JoinDialogCancelLabel = "Cancel"
HandsRegisteredMessage = "Your hands {{.HandsStr}} are registered with janken game ({{.ID}})."

# Config
ConfigDialogTitle = "Config"
ConfigDialogSubmitLabel = "Save"
ConfigDialogMaxRoundsLabel = "Max rounds"
ConfigDialogDestroyLabel = "Destroy this game"
JankenGameDestroyedMessage = "This janken game was destroyed by @{{.Username}}."
ConfigPermissionErrorMessage = "Failed to open the configration dialog. The creator of this game or the administrator can configure the game."

# Result
ResultTableRankLabel = "Rank"
ResultTableUsernameLabel = "Username"
ResultTableHandsLabel = "Hands"
ResultTableTitle = "**Janken Game ({{.ID}})**\nResult\n"
ResultPermissionErrorMessage = "Failed to show the result of the janken game. The creator of this game or the administrator can show the result."
ResultNotEnoughParticipantsErrorMessage = "Failed to show the result of the janken game. Least 2 pariticipants are required."
