[ConfigPermissionErrorMessage]
hash = "sha1-0837eda5aabd185e3225d367ad8b0a6b52793d52"
other = "設定ダイアログを開けませんでした。作成者か管理者のみが設定を変更できます"

[FailedToGetStoredGameErrorMessage]
hash = "sha1-9d63f28b9f05825410d063e69f19dbb98a1b19d6"
other = "ゲームデータの取得に失敗しました。別のゲームを作成してみてください。"

[HandsRegisteredMessage]
hash = "sha1-cfe6e6a60b5645172300b86cbac279f3b8336b25"
other = "あなたの手 {{.HandsStr}} はジャンケンゲーム ({{.ID}}) に登録されました"

[ResultNotEnoughParticipantsErrorMessage]
hash = "sha1-4e42957aad8cdb3c7908cbfeac323682c29a1d39"
other = "ジャンケンゲームの結果を表示できませんでした。結果を表示するには最低2人の参加者が必要です"

[ResultPermissionErrorMessage]
hash = "sha1-5c2c5410d38c48e3b72fbddf452eb09891754287"
other = "ジャンケンゲームの結果を表示できませんでした。作成者か管理者のみが結果を表示できます"

[ResultTableHandsLabel]
hash = "sha1-1f8e3c7cd3b8e378bb574499955f0cb0c10fd926"
other = "手"

[ResultTableRankLabel]
hash = "sha1-dd48a1149548f0b07ddec97e040571c91978fbab"
other = "順位"

[ResultTableTitle]
hash = "sha1-dd640e0fc8bb002e237260ef6859b75e43c2a141"
other = "**ジャンケンゲーム ({{.ID}})**\n結果\n"

[ResultTableUsernameLabel]
hash = "sha1-84c29015de33e5d22422382a372caba5c58f8c01"
other = "ユーザー名"

[configDialogDestroyLabel]
hash = "sha1-212158223d9cad100f46c2c29a280af21d582a28"
other = "ゲームの削除"

[configDialogMaxRoundsLabel]
hash = "sha1-116ee54b2faa5d0d387383edb426c890d153161e"
other = "最大ジャンケン回数"

[configDialogSubmitLabel]
hash = "sha1-efc007a393f66cdb14d57d385822a3d9e36ef873"
other = "保存"

[configDialogTitle]
hash = "sha1-8851142da56fd885ce668a165b33fee7003e858d"
other = "設定"

[gameConfigButtonLabel]
hash = "sha1-8851142da56fd885ce668a165b33fee7003e858d"
other = "設定"

[gameDescription]
hash = "sha1-ef8cc8f8f1d9b8b5fdf8ebaadc617a49d5acad58"
other = "ジャンケンゲームに参加してください。\n参加者 ({{.participantsNum}}): {{.participantsStr}}"

[gameDestroyedMessage]
hash = "sha1-5dd21ab001eb1d2ec5a28a0b99cc1096d6e27f9d"
other = "このジャンケンゲームは @{{.Username}} に削除されました。"

[gameJoinButtonLabel]
hash = "sha1-e0d73143de80d17e82de2e017ac156ca3b9c4e01"
other = "参加"

[gameResultButtonLabel]
hash = "sha1-5faa59d4bc3756040b8ce9e673c09f929e6ee9ba"
other = "結果"

[gameTitle]
hash = "sha1-8e601f5ebdce7c86458a5f895aec999ae34271b3"
other = "ジャンケンゲーム ({{.ID}}) が @{{.Username}} によって作成されました。"

[joinDialogCancelLabel]
hash = "sha1-77dfd2135f4db726c47299bb55be26f7f4525a46"
other = "参加の取り消し"

[joinDialogHandElementHelp]
hash = "sha1-224286e783b32dfc9fa4dbc065d8acb08e765714"
other = "{{.Index}}手目を選んでください。"

[joinDialogHandElementLabel]
hash = "sha1-82a99e367bbb0c551a4e29b313aa5576f6780fe9"
other = "{{.Index}}手目"

[joinDialogHandPaper]
hash = "sha1-22d507f2ba74e43593de3ae3f550bf202c076adc"
other = "パー"

[joinDialogHandRock]
hash = "sha1-468d79c2e0229e3ef8a5592b4df3e148050fb828"
other = "グー"

[joinDialogHandScissors]
hash = "sha1-faf4c3ea4e2730f2e886b2ca47368bf27df1cf3e"
other = "チョキ"

[joinDialogSubmitLabel]
hash = "sha1-efc007a393f66cdb14d57d385822a3d9e36ef873"
other = "保存"

[joinDialogTitle]
hash = "sha1-9f230566933e33c6bd965dc5145000a994091bf5"
other = "ジャンケンゲームへの参加"
